[pytest]
markers =
    validate_csv: marks tests that validate CSV file content
    unmarked: automatically assigned to tests without explicit marks

# only collect files prefixed with test_
python_files = test_*.py

# HTML report generation
addopts = --html=report.html --self-contained-html

# Report Portal Configuration
rp_endpoint = https://reportportal.epam.com
rp_project = MARIIA_KOVAL_PERSONAL
rp_api_key = pytest-report_y9nr22HMRNCuv32cMz4r-N5uzYrZoraqKy3IlTmJkjuF6MuFNL8coEZ9jGAsVmR5
rp_launch = PyTest_Introduction_Tests
rp_launch_description = CSV validation tests for PyTest Introduction homework
rp_launch_attributes = suite:pytest introduction:csv